-- phpMyAdmin SQL Dump
-- version 4.7.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jul 25, 2018 at 09:07 PM
-- Server version: 5.6.39
-- PHP Version: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `aplegal`
--

-- --------------------------------------------------------

--
-- Table structure for table `model_legislations_dummy`
--

CREATE TABLE `model_legislations_dummy` (
  `mleg_id` int(11) NOT NULL,
  `title_of_model_legislation` longtext COLLATE utf8_unicode_ci NOT NULL,
  `text_of_model_legislation` longtext COLLATE utf8_unicode_ci NOT NULL,
  `summary` longtext COLLATE utf8_unicode_ci NOT NULL,
  `state` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `display_file_name` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `purpose` longtext COLLATE utf8_unicode_ci,
  `preamble` longtext COLLATE utf8_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `model_legislations_dummy`
--

INSERT INTO `model_legislations_dummy` (`mleg_id`, `title_of_model_legislation`, `text_of_model_legislation`, `summary`, `state`, `type`, `display_file_name`, `purpose`, `preamble`) VALUES
(1, 'Dummy Legislation', 'There is a lot to be said about dummies and this legislation does not hold back.', 'Legislation that talks about dummies.', 'AZ', NULL, NULL, NULL, NULL),
(2, 'Dummy Legislation 2', 'There is a lot to be said about dummies and this legislation does not hold back.', 'Legislation that talks about dummies.', 'AZ', NULL, NULL, NULL, NULL),
(3, 'cqfh', 'Voluptatem modi exercitationem quia fugit. Esse consequatur aliquam reprehenderit consequatur et veniam. Quisquam reiciendis magni ut accusamus. Placeat voluptate harum officia.', 'DOTH THE LITTLE BUSY BEE,\" but it puzzled her a good thing!\' she said to the voice of the house!\' (Which was very deep, or she fell past it. \'Well!\' thought Alice to herself. At this moment Five,.', 'NorthCarolina', '041', 'voluptatem', 'Queen: so she felt sure it would make with the day and night! You see the Hatter asked triumphantly. Alice did not answer, so Alice soon came upon a neat little house, on the slate. \'Herald, read.', NULL),
(4, 'thwn', 'Delectus autem ut molestiae cumque atque vitae iure. Nostrum sint consequatur atque vero vel. Repudiandae quis ex repellat ut et ad.', 'I grow at a reasonable pace,\' said the Pigeon; \'but if you\'ve seen them at last, and they went up to the garden at once; but, alas for poor Alice! when she turned to the fifth bend, I think?\' \'I had.', 'Kentucky', '216', 'nisi', 'Alice\'s shoulder as she could see, when she looked up eagerly, half hoping that they would go, and broke to pieces against one of the way--\' \'THAT generally takes some time,\' interrupted the.', NULL),
(5, 'jgvx', 'Nobis natus consequatur fugit. Est consectetur expedita eligendi delectus delectus reprehenderit et. Eligendi mollitia aliquid id quia debitis. Numquam et et distinctio ut et doloremque perspiciatis ducimus.', 'I have done that?\' she thought. \'I must go back by railway,\' she said these words her foot slipped, and in a great hurry. An enormous puppy was looking at them with one finger for the Dormouse,\'.', 'Ohio', '967', 'sint', 'Gryphon in an impatient tone: \'explanations take such a thing before, and she tried hard to whistle to it; but she could not remember ever having heard of one,\' said Alice. \'I\'m glad they don\'t seem.', NULL),
(6, 'djfg', 'Quas et magnam quisquam nisi iste. Temporibus ut officiis fugit ut. Doloremque in voluptatibus illo id.', 'Alice dodged behind a great hurry to change the subject,\' the March Hare had just upset the milk-jug into his cup of tea, and looked along the course, here and there stood the Queen of Hearts were.', 'Oregon', '887', 'labore', 'Dormouse denied nothing, being fast asleep. \'After that,\' continued the King. The next witness was the first to speak. \'What size do you call it purring, not growling,\' said Alice. \'Of course you.', NULL),
(7, 'cwsp', 'Illo magnam quisquam quis dolor. Accusamus voluptatem minima omnis voluptatibus ut.', 'Alice loudly. \'The idea of having nothing to do: once or twice, and shook itself. Then it got down off the mushroom, and her eyes filled with tears again as quickly as she went hunting about, and.', 'Alaska', '083', 'qui', 'YOU are, first.\' \'Why?\' said the Gryphon, \'she wants for to know what it might belong to one of the room. The cook threw a frying-pan after her as she could do, lying down on their hands and feet,.', NULL),
(8, 'liml', 'Id mollitia sed quos sapiente ut. Aliquid itaque tenetur eum. In dolores mollitia natus id. Qui dolore qui amet quis.', 'I goes like a star-fish,\' thought Alice. The poor little thing grunted in reply (it had left off sneezing by this time). \'Don\'t grunt,\' said Alice; \'I might as well as she spoke; \'either you or your.', 'Virginia', '709', 'ut', 'Alice. \'But you\'re so easily offended!\' \'You\'ll get used up.\' \'But what did the Dormouse crossed the court, by the soldiers, who of course was, how to get an opportunity of saying to her very much.', NULL),
(9, 'lmvm', 'Qui porro consequatur dolor nam porro. Recusandae vitae eos beatae minus ratione at est at. Esse voluptatum quaerat culpa occaecati non aut similique molestias.', 'Gryphon, and the executioner myself,\' said the voice. \'Fetch me my gloves this moment!\' Then came a rumbling of little pebbles came rattling in at once.\' And in she went. Once more she found to be.', 'RhodeIsland', '957', 'fuga', 'Gryphon, half to herself, \'because of his pocket, and pulled out a history of the e--e--evening, Beautiful, beautiful Soup!\' CHAPTER XI. Who Stole the Tarts? The King and Queen of Hearts, he stole.', NULL),
(10, 'limm', 'Fugit ab sunt sapiente consequatur consequatur placeat. Quia dignissimos quo animi molestiae. Voluptate fuga eos ipsum autem quidem. Ea autem repudiandae qui quasi rerum commodi.', 'Bill! I wouldn\'t be so kind,\' Alice replied, rather shyly, \'I--I hardly know, sir, just at first, the two creatures, who had been broken to pieces. \'Please, then,\' said the Queen, turning purple. \'I.', 'Iowa', '858', 'qui', 'I\'m never sure what I\'m going to dive in among the bright eager eyes were looking over his shoulder as he spoke. \'UNimportant, of course, I meant,\' the King said to the Knave. The Knave shook his.', NULL),
(11, 'sqqf', 'Error tenetur est magnam odio ipsa sint. Minima quis et reprehenderit consequatur eligendi dolor. Excepturi ut provident quam aliquam perspiciatis. Asperiores unde et in blanditiis similique ut et.', 'Lobster; I heard him declare, \"You have baked me too brown, I must sugar my hair.\" As a duck with its tongue hanging out of THIS!\' (Sounds of more broken glass.) \'Now tell me, Pat, what\'s that in.', 'Kentucky', '171', 'ut', 'Alice like the name: however, it only grinned a little bottle that stood near. The three soldiers wandered about in the distance, and she walked on in a game of play with a lobster as a boon, Was.', NULL),
(12, 'viyy', 'Eius reprehenderit dolorem eum et sequi praesentium minus. Qui perspiciatis at ut aut voluptatem reiciendis dolores quia. Incidunt quas expedita exercitationem sint laborum. Ut nostrum quo omnis autem at aut laudantium.', 'The Gryphon sat up and straightening itself out again, so that by the time he had taken advantage of the miserable Mock Turtle. \'Certainly not!\' said Alice thoughtfully: \'but then--I shouldn\'t be.', 'SouthCarolina', '762', 'modi', 'Queen will hear you! You see, she came suddenly upon an open place, with a little glass table. \'Now, I\'ll manage better this time,\' she said, as politely as she could remember about ravens and.', NULL),
(13, 'ilcu', 'Enim maiores provident eligendi voluptatum. Deleniti eaque ex labore molestias sed. Sed amet totam aut. Sunt necessitatibus sed excepturi sed atque eveniet.', 'Gryphon, and, taking Alice by the Hatter, and he says it\'s so useful, it\'s worth a hundred pounds! He says it kills all the jurymen on to her daughter \'Ah, my dear! I shall only look up in great.', 'Kentucky', '974', 'doloribus', 'However, she got to the garden with one finger pressed upon its nose. The Dormouse shook itself, and began to repeat it, but her voice sounded hoarse and strange, and the moon, and memory, and.', NULL),
(14, 'ihcx', 'Nemo odit consequuntur laborum aut. Nihil illo sint beatae tenetur ut voluptatem placeat. Neque ut et sed voluptas officia nobis. Dolor dolore quis hic ea amet voluptatem.', 'Mock Turtle. \'Very much indeed,\' said Alice. \'Then you keep moving round, I suppose?\' said Alice. \'Anything you like,\' said the Hatter. \'Nor I,\' said the Mouse heard this, it turned a corner, \'Oh my.', 'Hawaii', '064', 'quis', 'I\'ll stay down here with me! There are no mice in the sea, some children digging in the same words as before, \'and things are \"much of a good way off, and she jumped up on to the part about her.', NULL),
(15, 'mucf', 'Totam est impedit ut accusantium facere. Quibusdam explicabo sunt nisi qui. Est velit provident et aut aut iusto ut.', 'Presently the Rabbit actually TOOK A WATCH OUT OF ITS WAISTCOAT-POCKET, and looked very anxiously into its face was quite tired and out of the garden, called out in a thick wood. \'The first thing.', 'Oklahoma', '583', 'reprehenderit', 'I look like one, but it was too slippery; and when Alice had got so much contradicted in her pocket, and was gone across to the tarts on the ground as she could, and soon found out that one of the.', NULL),
(16, 'gqiz', 'Dicta quae debitis nulla. Laudantium in optio ducimus et tenetur sunt a. Est vero odio nam aut sed.', 'I know is, something comes at me like that!\' But she did it so yet,\' said the Gryphon: and it set to work shaking him and punching him in the kitchen. \'When I\'M a Duchess,\' she said this last remark.', 'Hawaii', '974', 'rerum', 'I give it up,\' Alice replied: \'what\'s the answer?\' \'I haven\'t the slightest idea,\' said the Mock Turtle drew a long hookah, and taking not the right words,\' said poor Alice, \'when one wasn\'t always.', NULL),
(17, 'rzlc', 'Deleniti sed veniam ipsam sed. Velit aut dolor quia corrupti. Laboriosam sequi voluptatum neque quisquam omnis sed perspiciatis. Molestiae dolorum tempore velit perferendis et voluptates.', 'Alice, as she tucked it away under her arm, and timidly said \'Consider, my dear: she is only a mouse that had slipped in like herself. \'Would it be of very little use without my shoulders. Oh, how I.', 'Colorado', '579', 'illo', 'Hatter. \'Does YOUR watch tell you how it was the Hatter. This piece of evidence we\'ve heard yet,\' said the Mock Turtle replied, counting off the mushroom, and raised herself to about two feet high,.', NULL),
(18, 'neme', 'Quia nisi aut accusamus error quam odit voluptatibus. A assumenda consectetur tempore eos voluptatum cum perspiciatis laboriosam.', 'Duchess, \'and that\'s the queerest thing about it.\' \'She\'s in prison,\' the Queen merely remarking that a moment\'s pause. The only things in the house, quite forgetting that she ought not to lie down.', 'Georgia', '124', 'voluptatum', 'The executioner\'s argument was, that if you were all shaped like ears and the poor little thing grunted in reply (it had left off writing on his spectacles. \'Where shall I begin, please your.', NULL),
(19, 'hnzy', 'Modi soluta placeat eligendi veniam. Nobis eos nihil consequatur dignissimos aut optio minima doloribus. Est eaque fugit modi non. Magni omnis illum sint non.', 'Alice remarked. \'Oh, you foolish Alice!\' she answered herself. \'How can you learn lessons in the schoolroom, and though this was of very little use without my shoulders. Oh, how I wish I could show.', 'NewJersey', '468', 'nulla', 'Alice indignantly, and she felt that it is!\' \'Why should it?\' muttered the Hatter. \'Stolen!\' the King in a piteous tone. And the moral of that is--\"Birds of a muchness?\' \'Really, now you ask me,\'.', NULL),
(20, 'jbvv', 'Et et non sit fugit porro voluptates mollitia. Non cumque et enim soluta nisi.', 'I was thinking I should think you\'ll feel it a violent shake at the Mouse\'s tail; \'but why do you know what to beautify is, I can\'t tell you my adventures--beginning from this side of WHAT?\' thought.', 'Idaho', '058', 'optio', 'Alice. \'Reeling and Writhing, of course, to begin again, it was just beginning to grow up again! Let me see: four times seven is--oh dear! I wish you were or might have been a holiday?\' \'Of course.', NULL),
(21, 'danm', 'Eum harum rerum quia asperiores. Laborum enim sint aut vel deserunt in. Aut molestias exercitationem modi voluptatum distinctio at veritatis.', 'Alice; \'that\'s not at all the arches are gone from this side of the fact. \'I keep them to be ashamed of yourself,\' said Alice, very much what would be grand, certainly,\' said Alice to find herself.', 'Nebraska', '557', 'blanditiis', 'Half-past one, time for dinner!\' (\'I only wish people knew that: then they wouldn\'t be in a confused way, \'Prizes! Prizes!\' Alice had got its neck nicely straightened out, and was just in time to.', NULL),
(22, 'hdwl', 'Eius est tenetur voluptatum ut sit eaque voluptatum. Consectetur sed nulla amet. Minima dicta eligendi amet et tempora amet. Magnam quae aut inventore corporis provident et totam.', 'Don\'t let me help to undo it!\' \'I shall do nothing of the garden, called out \'The Queen! The Queen!\' and the pattern on their slates, when the Rabbit say to itself \'Then I\'ll go round and swam.', 'Nevada', '679', 'temporibus', 'White Rabbit as he spoke. \'UNimportant, of course, I meant,\' the King sharply. \'Do you take me for asking! No, it\'ll never do to come yet, please your Majesty?\' he asked. \'Begin at the number of.', NULL),
(23, 'efra', 'Earum animi impedit error ipsum rem repellendus. Quo qui temporibus omnis porro perferendis. Qui eius tempora itaque rerum.', 'White Rabbit returning, splendidly dressed, with a large kitchen, which was a little way forwards each time and a large rabbit-hole under the sea,\' the Gryphon replied rather crossly: \'of course you.', 'Illinois', '688', 'ut', 'Alice noticed with some surprise that the meeting adjourn, for the accident of the e--e--evening, Beautiful, beautiful Soup!\' CHAPTER XI. Who Stole the Tarts? The King and Queen of Hearts, carrying.', NULL),
(24, 'dlik', 'Rerum accusantium nam sequi rem earum est voluptatem. Aut nemo repellendus fuga delectus. Placeat minus aut facere incidunt dolorem voluptatum. Ex aspernatur fuga perferendis. Alias velit quia assumenda maiores.', 'HIS time of life. The King\'s argument was, that if you were or might have been a RED rose-tree, and we won\'t talk about cats or dogs either, if you don\'t know where Dinn may be,\' said the King. The.', 'Colorado', '963', 'ut', 'CHAPTER IX. The Mock Turtle\'s Story \'You can\'t think how glad I am very tired of being such a thing as \"I eat what I see\"!\' \'You might just as if she had never heard it say to this: so she went on.', NULL),
(25, 'avjj', 'Dolor libero possimus quidem numquam. Occaecati ut dicta temporibus omnis nulla repudiandae aliquid. Voluptas quia voluptas occaecati quidem minus voluptas.', 'Alice! when she had not as yet had any sense, they\'d take the hint; but the cook and the happy summer days. THE.', 'Hawaii', '618', 'at', 'Hatter: \'but you could manage it?) \'And what an ignorant little girl or a watch to take MORE than nothing.\' \'Nobody asked YOUR opinion,\' said Alice. \'Of course it was,\' the March Hare, \'that \"I.', NULL),
(26, 'rmpt', 'Voluptas est consequatur in ut autem ipsa ea. Sequi ipsam harum architecto nihil. Minus velit et quas laboriosam odit voluptas quam. Atque voluptas mollitia accusantium ipsa placeat.', 'OUTSIDE.\' He unfolded the paper as he spoke, and added \'It isn\'t a bird,\' Alice remarked. \'Oh, you foolish Alice!\' she answered herself. \'How can you learn lessons in here? Why, there\'s hardly room.', 'Maine', '444', 'inventore', 'It means much the same as the jury wrote it down into its eyes were nearly out of a tree in the other: the only difficulty was, that if something wasn\'t done about it just grazed his nose, you.', NULL),
(27, 'ujxu', 'Numquam magnam mollitia quis et hic ipsam. Iusto non eos omnis itaque veniam. Nesciunt quia eveniet soluta.', 'So Alice began to cry again, for she could not possibly reach it: she could see it trot away quietly into the book her sister kissed her, and she did not feel encouraged to ask his neighbour to tell.', 'NorthDakota', '164', 'quam', 'Soup of the tale was something like this:-- \'Fury said to the table to measure herself by it, and talking over its head. \'Very uncomfortable for the rest of my own. I\'m a deal faster than it does.\'.', NULL),
(28, 'ojrm', 'Odio aut voluptatem et nihil quasi soluta. Voluptatem deleniti unde facilis omnis voluptas voluptas. Architecto ab explicabo molestiae aliquid laborum. Odit laborum ad placeat quisquam ut animi rerum. Praesentium doloribus consequatur neque temporibus quo eum repellendus.', 'However, she got to go near the looking-glass. There was exactly the right words,\' said poor Alice, \'it would have done that, you know,\' the Hatter were having tea at it: a Dormouse was sitting on.', 'Arkansas', '950', 'in', 'Duchess, \'chop off her head!\' the Queen put on your head-- Do you think you might catch a bat, and that\'s very like a serpent. She had already heard her voice sounded hoarse and strange, and the.', NULL),
(29, 'dazw', 'Nulla qui quam ducimus et fugiat asperiores optio. Qui amet libero sequi porro nisi eveniet sit. Veritatis dolore illum est. Ut omnis beatae dolore quis.', 'The Pool of Tears \'Curiouser and curiouser!\' cried Alice again, for this curious child was very likely it can talk: at any rate, there\'s no name signed at the bottom of the month is it?\' he said,.', 'California', '714', 'in', 'I\'ll be jury,\" Said cunning old Fury: \"I\'ll try the experiment?\' \'HE might bite,\' Alice cautiously replied, not feeling at all this grand procession, came THE KING AND QUEEN OF HEARTS. Alice was a.', NULL),
(30, 'kpnw', 'Vitae facilis qui aut asperiores ullam beatae dolor. Provident similique et excepturi inventore exercitationem molestiae et tenetur. Deleniti rerum voluptas est quaerat deserunt aut. Eum suscipit voluptatem corporis consectetur nihil.', 'I don\'t think,\' Alice went on, \'you see, a dog growls when it\'s pleased. Now I growl when I\'m angry. Therefore I\'m mad.\' \'I call it sad?\' And she began fancying the sort of thing that would happen:.', 'NewMexico', '255', 'dignissimos', 'The pepper when he pleases!\' CHORUS. \'Wow! wow! wow!\' \'Here! you may nurse it a little sharp bark just over her head was so ordered about in all my life!\' She had just upset the milk-jug into his.', NULL),
(31, 'ibag', 'Earum eius molestiae voluptatum sunt. Nisi eveniet ad numquam omnis.', 'Mock Turtle, who looked at Alice, and she very seldom followed it), and sometimes shorter, until she had sat down and make THEIR eyes bright and eager with many a strange tale, perhaps even with the.', 'SouthCarolina', '954', 'provident', 'I get\" is the same solemn tone, \'For the Duchess. \'I make you grow taller, and the little crocodile Improve his shining tail, And pour the waters of the teacups as the March Hare. \'Yes, please do!\'.', NULL),
(32, 'gugm', 'Aperiam aut voluptas consequatur deleniti. Dolor officiis ipsam ipsum libero sit sit. Et tenetur saepe quo aut. Numquam et fugit et laudantium numquam suscipit.', 'Gryphon whispered in a low, timid voice, \'If you can\'t take more.\' \'You mean you can\'t be civil, you\'d better ask HER about it.\' (The jury all looked puzzled.) \'He must have been that,\' said the.', 'Nevada', '051', 'labore', 'There were doors all round the thistle again; then the Mock Turtle, and to hear his history. I must be off, then!\' said the Hatter: \'as the things between whiles.\' \'Then you should say what you.', NULL),
(33, 'satd', 'Alias magni aut consequatur. Fuga voluptates corrupti suscipit. Nihil est labore quia asperiores totam est saepe. Eum iure qui dolor.', 'Alice, looking down at once, and ran till she too began dreaming after a pause: \'the reason is, that there\'s any one of the door began sneezing all at once. \'Give your evidence,\' the King hastily.', 'Georgia', '746', 'illum', 'Cheshire cat,\' said the King eagerly, and he called the Queen, \'and take this child away with me,\' thought Alice, and, after folding his arms and legs in all my life, never!\' They had a pencil that.', NULL),
(34, 'gkvy', 'Velit assumenda ut sed voluptas voluptas. In alias excepturi facilis omnis. Et in sed aut ratione nemo deleniti. Vel eum omnis ut velit.', 'White Rabbit was still in existence; \'and now for the immediate adoption of more energetic remedies--\' \'Speak English!\' said the King said to the table, but it just now.\' \'It\'s the thing Mock Turtle.', 'SouthDakota', '229', 'consequatur', 'March Hare, \'that \"I breathe when I sleep\" is the same thing a Lobster Quadrille is!\' \'No, indeed,\' said Alice. \'You did,\' said the Duchess. \'I make you grow taller, and the words \'EAT ME\' were.', NULL),
(35, 'syon', 'Sint quas repellendus laborum iure ipsam. Modi qui voluptas quia soluta unde iure ipsam. Doloribus ut est sunt. Necessitatibus nemo sed et.', 'Alice, \'to speak to this mouse? Everything is so out-of-the-way down here, that I should understand that better,\' Alice said nothing; she had succeeded in bringing herself down to them, they were.', 'Utah', '732', 'nam', 'NOT be an advantage,\' said Alice, \'we learned French and music.\' \'And washing?\' said the Hatter went on eagerly. \'That\'s enough about lessons,\' the Gryphon said, in a hurry that she never knew so.', NULL),
(36, 'dqxk', 'Aut earum autem excepturi accusantium qui officiis necessitatibus. Dolorum qui animi illum enim amet velit. Id rerum qui debitis amet nemo. Rem nemo cumque eos aliquid cum.', 'For he can thoroughly enjoy The pepper when he finds out who was talking. \'How CAN I have dropped them, I wonder?\' As she said to the King, and the fall was over. Alice was soon submitted to by the.', 'Kansas', '884', 'pariatur', 'I must be a very respectful tone, but frowning and making quite a commotion in the book,\' said the Mock Turtle went on, \'if you don\'t even know what you would have called him a fish)--and rapped.', NULL),
(37, 'qojx', 'Dicta voluptas enim iusto fuga aut. Qui ab facilis molestias dolorem maiores qui. Officiis amet ducimus cum deleniti maiores rem. Corporis doloribus ut rem est reiciendis.', 'Dormouse. \'Don\'t talk nonsense,\' said Alice to herself, and nibbled a little timidly, for she felt certain it must be getting somewhere near the door of the other side of WHAT? The other side of the.', 'RhodeIsland', '023', 'quod', 'I am now? That\'ll be a walrus or hippopotamus, but then she walked down the hall. After a while, finding that nothing more to be otherwise than what you would seem to come down the middle, wondering.', NULL),
(38, 'xecp', 'Enim ipsa fugit est ut distinctio suscipit. Enim ipsam omnis cum. Iste corporis libero alias. Ducimus cumque non quam ipsum itaque.', 'The Duchess took her choice, and was going to do it! Oh dear! I\'d nearly forgotten to ask.\' \'It turned into a large cat which was sitting between them, fast asleep, and the poor child, \'for I can\'t.', 'Wisconsin', '996', 'sunt', 'Last came a rumbling of little Alice herself, and fanned herself with one of the treat. When the sands are all pardoned.\' \'Come, THAT\'S a good character, But said I didn\'t!\' interrupted Alice. \'You.', NULL),
(39, 'amhz', 'Dolorum nesciunt et eum modi. Molestiae corporis natus rerum totam ab. Qui sunt aut et voluptatem quis sunt. Aut et vel iure qui minima. Temporibus numquam ratione dolorum rerum sed porro.', 'Mouse replied rather crossly: \'of course you know what a long breath, and said \'That\'s very curious!\' she thought. \'I must be kind to them,\' thought Alice, \'they\'re sure to do with this creature.', 'Connecticut', '560', 'alias', 'Gryphon never learnt it.\' \'Hadn\'t time,\' said the last words out loud, and the blades of grass, but she gained courage as she did not seem to dry me at all.\' \'In that case,\' said the Cat, and.', NULL),
(40, 'syvu', 'Rem reprehenderit maiores qui est at. Necessitatibus rem et dolorem provident. Fuga dignissimos facere sint at aliquid laboriosam.', 'Alice alone with the bread-and-butter getting so thin--and the twinkling of the other guinea-pig cheered, and was delighted to find that she was holding, and she ran off at once to eat her up in a.', 'Illinois', '536', 'sequi', 'Kings and Queens, and among them Alice recognised the White Rabbit with pink eyes ran close by it, and kept doubling itself up very sulkily and crossed over to the door. \'Call the first to speak..', NULL),
(41, 'jbhw', 'Aut fugit cum sed placeat doloribus voluptas. Molestiae ut veritatis voluptatum quia eum ipsa. A debitis eaque porro. Fuga placeat velit numquam repudiandae dolor vitae.', 'Derision.\' \'I never could abide figures!\' And with that she was playing against herself, for she was quite silent for a minute or two to think to herself, \'I wonder how many hours a day is very.', 'Hawaii', '189', 'sapiente', 'I am now? That\'ll be a person of authority among them, called out, \'Sit down, all of you, and must know better\'; and this was of very little use without my shoulders. Oh, how I wish you would seem.', NULL),
(42, 'pmxy', 'Sunt facere aut occaecati pariatur sed. Natus dolorem debitis vel ducimus natus cupiditate. Sunt qui ea laborum perferendis sit harum odio. Et quidem minus doloribus accusamus illo neque iure.', 'Mabel after all, and I don\'t want YOU with us!\"\' \'They were obliged to write with one eye, How the Owl had the best plan.\' It sounded an excellent plan, no doubt, and very soon finished it off. \'If.', 'Missouri', '412', 'perferendis', 'Cat, and vanished. Alice was not going to begin lessons: you\'d only have to turn into a line along the course, here and there. There was no time she\'d have everybody executed, all round. \'But she.', NULL),
(43, 'byww', 'Cupiditate voluptatem mollitia ratione nesciunt ut blanditiis. Amet corrupti doloremque qui eos sit ullam illo optio. Maiores aut ut et consequatur saepe qui veritatis. Nobis facilis voluptas vitae sequi provident suscipit. Quo explicabo officiis veniam iusto quisquam incidunt adipisci.', 'The Mouse did not notice this question, but hurriedly went on, half to Alice. \'What sort of way to fly up into a butterfly, I should like to try the patience of an oyster!\' \'I wish I had it written.', 'Utah', '992', 'optio', 'I will prosecute YOU.--Come, I\'ll take no denial; We must have been changed for Mabel! I\'ll try if I can say.\' This was quite tired and out of sight: then it watched the Queen shouted at the top of.', NULL),
(44, 'fyhv', 'Qui modi quos veniam doloremque expedita ad. Voluptatem enim magnam ut ducimus. Porro dolorem quaerat laudantium cupiditate rerum ad temporibus et. Qui temporibus repellat libero quam quisquam.', 'Queen, tossing her head through the wood. \'It\'s the first to break the silence. \'What day of the water, and seemed to her ear, and whispered \'She\'s under sentence of execution. Then the Queen said.', 'Virginia', '187', 'omnis', 'HAVE you been doing here?\' \'May it please your Majesty,\' said the one who had followed him into the earth. Let me see: four times five is twelve, and four times five is twelve, and four times six is.', NULL),
(45, 'sbnh', 'Explicabo ipsam quo consectetur nihil et corporis. Est dolorem incidunt enim saepe sequi repellendus. Officiis impedit officiis et optio expedita illo. Tenetur vel consequatur unde minima.', 'Gryphon in an agony of terror. \'Oh, there goes his PRECIOUS nose\'; as an unusually large saucepan flew close by it, and they repeated their arguments to her, \'if we had the door with his head!\"\'.', 'Wisconsin', '097', 'aspernatur', 'King, the Queen, who were lying on the other paw, \'lives a Hatter: and in despair she put them into a butterfly, I should like to see that the Mouse in the air. Even the Duchess to play with, and.', NULL),
(46, 'eijn', 'Cum qui laudantium fuga consectetur enim esse qui et. Quibusdam id architecto consequatur esse provident. Sed eius vitae alias corporis temporibus eum.', 'France-- Then turn not pale, beloved snail, but come and join the dance. Would not, could not, could not, would not open any of them. However, on the stairs. Alice knew it was good practice to say.', 'WestVirginia', '571', 'temporibus', 'At last the Gryphon replied rather crossly: \'of course you don\'t!\' the Hatter replied. \'Of course it was,\' the March Hare moved into the garden door. Poor Alice! It was so large in the pictures of.', NULL),
(47, 'ynbs', 'Qui ut earum dolorum. Reprehenderit doloribus autem voluptate autem. Cumque earum sint qui dolores nesciunt ut. Quia non ad nam nam magni labore dolorem.', 'March Hare,) \'--it was at in all directions, \'just like a Jack-in-the-box, and up I goes like a steam-engine when she went on, \'What\'s your name, child?\' \'My name is Alice, so please your Majesty,\'.', 'Delaware', '465', 'accusantium', 'Alice desperately: \'he\'s perfectly idiotic!\' And she began again: \'Ou est ma chatte?\' which was the White Rabbit. She was looking for it, she found her head made her feel very uneasy: to be afraid.', NULL),
(48, 'jrhj', 'Fugiat ex id sequi suscipit repudiandae voluptatem. Aperiam qui est id distinctio et ipsum fugiat. Ea quisquam ut sequi eveniet voluptates. Quia voluptas libero reprehenderit suscipit fugit natus ea harum.', 'Queen\'s absence, and were quite dry again, the cook tulip-roots instead of the house!\' (Which was very fond of beheading people here; the great hall, with the lobsters to the Mock Turtle,.', 'Louisiana', '360', 'rerum', 'Gryphon: and it said nothing. \'Perhaps it doesn\'t matter a bit,\' said the King, \'that only makes the matter with it. There could be beheaded, and that he had to double themselves up and.', NULL),
(49, 'cudu', 'Nulla enim voluptates dolorem saepe. Necessitatibus libero quo itaque sit culpa et qui voluptas. Ad voluptatibus totam eos officia. Praesentium ut accusamus nisi.', 'Pray, what is the same thing,\' said the King. (The jury all looked puzzled.) \'He must have been a holiday?\' \'Of course not,\' Alice replied very solemnly. Alice was only a child!\' The Queen smiled.', 'Georgia', '653', 'est', 'The baby grunted again, and looking anxiously about as curious as it turned a back-somersault in at once.\' However, she got into the way wherever she wanted much to know, but the great wonder is,.', NULL),
(50, 'cqfg', 'Ut magnam omnis esse accusamus tempore. Quia rerum velit illum est ea veritatis et. Quia commodi quam nemo maiores expedita qui. Repellendus aut soluta voluptatum veniam veniam quidem.', 'HIS time of life. The King\'s argument was, that her flamingo was gone across to the seaside once in a great crowd assembled about them--all sorts of things, and she, oh! she knows such a thing..', 'Missouri', '141', 'eos', 'Mouse, who was talking. \'How CAN I have none, Why, I do wonder what they said. The executioner\'s argument was, that anything that looked like the tone of great relief. \'Now at OURS they had to run.', NULL),
(51, 'rruv', 'Dolores sint molestiae maxime non enim. Qui neque sed nobis. Repudiandae itaque magnam voluptatem nisi tempore.', 'However, she did not much surprised at her side. She was close behind us, and he\'s treading on her lap as if she had drunk half the bottle, she found this a very interesting dance to watch,\' said.', 'Kansas', '755', 'delectus', 'Alice could hardly hear the words:-- \'I speak severely to my right size: the next verse,\' the Gryphon replied very gravely. \'What else had you to leave the court; but on second thoughts she decided.', NULL),
(52, 'poro', 'Architecto sunt enim dignissimos voluptatem reiciendis. Eaque quas quia ipsam temporibus in ipsa. Quaerat minus molestiae qui exercitationem voluptas. Aut quo dolor est ipsa atque labore. Ut assumenda vel minus reprehenderit repellendus assumenda ea.', 'There seemed to be trampled under its feet, \'I move that the way the people that walk with their fur clinging close to the end of trials, \"There was some attempts at applause, which was lit up by.', 'Hawaii', '085', 'neque', 'Bill! I wouldn\'t say anything about it, you know.\' He was looking about for it, she found that her shoulders were nowhere to be a grin, and she tried another question. \'What sort of present!\'.', NULL),
(53, 'dyhi', 'Ab ea vel pariatur voluptatibus. Aut sunt optio doloribus assumenda sit et. Officiis iusto ut placeat non vel eligendi. Cum quasi quaerat non dolorem numquam labore. Deserunt distinctio ab et libero.', 'Alice, and she trembled till she heard it before,\' said the Rabbit whispered in a mournful tone, \'he won\'t do a thing I ever was at in all directions, \'just like a snout than a pig, and she looked.', 'Indiana', '660', 'et', 'I\'ll be jury,\" Said cunning old Fury: \"I\'ll try the whole pack rose up into hers--she could hear the rattle of the sort,\' said the Pigeon went on, very much of it now in sight, and no more to come,.', NULL),
(54, 'xivb', 'Illum autem adipisci repudiandae repudiandae ipsam et. In aut expedita qui quasi tempore aut ipsum. Quas nulla ut quia laboriosam dolorum.', 'Alice, \'and if it please your Majesty,\' he began, \'for bringing these in: but I THINK I can creep under the sea--\' (\'I haven\'t,\' said Alice)--\'and perhaps you were or might have been was not an.', 'Oregon', '904', 'sed', 'Rabbit\'s little white kid gloves while she was losing her temper. \'Are you content now?\' said the Footman. \'That\'s the most interesting, and perhaps after all it might be hungry, in which case it.', NULL),
(55, 'aeyt', 'Dignissimos et doloribus eum voluptatem quia qui. Blanditiis voluptatem fugiat commodi neque quis quaerat. Veritatis ducimus quia rem minima et quisquam.', 'Alice, (she had kept a piece of rudeness was more hopeless than ever: she sat down in a low voice, \'Your Majesty must cross-examine THIS witness.\' \'Well, if I only wish they COULD! I\'m sure _I_.', 'Texas', '585', 'numquam', 'When she got back to the beginning again?\' Alice ventured to ask. \'Suppose we change the subject. \'Go on with the bread-and-butter getting so used to it in with the dream of Wonderland of long ago:.', NULL),
(56, 'gthx', 'Mollitia odit occaecati eum accusantium pariatur. Sed quasi aut eos iure sunt. Debitis natus quis soluta voluptas consequatur et accusamus.', 'ALL RETURNED FROM HIM TO YOU,\"\' said Alice. \'Anything you like,\' said the Duck: \'it\'s generally a frog or a serpent?\' \'It matters a good many little girls in my time, but never ONE with such a thing.', 'Montana', '574', 'reprehenderit', 'Cat, and vanished again. Alice waited patiently until it chose to speak first, \'why your cat grins like that?\' \'It\'s a Cheshire cat,\' said the Gryphon: and it put the Lizard in head downwards, and.', NULL),
(57, 'ktyb', 'Voluptatum veniam culpa consectetur sequi inventore ab cumque. Nulla quidem blanditiis deleniti et.', 'Dormouse go on till you come to the executioner: \'fetch her here.\' And the moral of that dark hall, and close to her ear. \'You\'re thinking about something, my dear, and that makes you forget to.', 'RhodeIsland', '978', 'optio', 'SIT down,\' the King had said that day. \'That PROVES his guilt,\' said the Cat, \'if you don\'t know one,\' said Alice. \'Come, let\'s try the experiment?\' \'HE might bite,\' Alice cautiously replied, not.', NULL),
(58, 'dvxz', 'Provident sint deserunt optio quo. Et eligendi itaque nemo. Est repellendus sint architecto beatae eveniet. Tempora nobis nobis consectetur.', 'I will prosecute YOU.--Come, I\'ll take no denial; We must have been a holiday?\' \'Of course twinkling begins with an M?\' said Alice. \'That\'s very curious!\' she thought. \'But everything\'s curious.', 'Nebraska', '590', 'vel', 'Mouse heard this, it turned a back-somersault in at the mushroom for a baby: altogether Alice did not sneeze, were the verses the White Rabbit hurried by--the frightened Mouse splashed his way.', NULL),
(59, 'zari', 'Eos quae dolorum earum ut. Corrupti sit et est quibusdam.', 'Conqueror, whose cause was favoured by the whole place around her became alive with the words don\'t FIT you,\' said the Cat. \'I said pig,\' replied Alice; \'and I do it again and again.\' \'You are not.', 'Alabama', '003', 'minus', 'IN the well,\' Alice said very humbly; \'I won\'t interrupt again. I dare say there may be ONE.\' \'One, indeed!\' said Alice, a good way off, panting, with its arms folded, quietly smoking a long.', NULL),
(60, 'lhby', 'Corporis ab qui qui et voluptatem nam consequatur. Suscipit autem velit doloremque perspiciatis accusamus veniam minima. Velit quas delectus deserunt quaerat nulla magnam. Sit aut et sit aut natus.', 'Dormouse into the roof of the sea.\' \'I couldn\'t help it,\' said the Dodo said, \'EVERYBODY has won, and all must have got in as well,\' the Hatter grumbled: \'you shouldn\'t have put it more clearly,\'.', 'Colorado', '520', 'laudantium', 'I ever heard!\' \'Yes, I think I may as well as she could, for the baby, it was in the lap of her voice. Nobody moved. \'Who cares for you?\' said the Gryphon. \'How the creatures argue. It\'s enough to.', NULL),
(61, 'frbk', 'Consectetur veritatis ut rem quo est nemo. Illum sit nobis voluptatem. Cumque ab cumque nemo sit nobis eveniet hic blanditiis.', 'Then came a little of it?\' said the King. On this the whole thing, and she went on, \'if you don\'t know what \"it\" means.\' \'I know what it was: she was quite silent for a minute, while Alice thought.', 'Iowa', '471', 'corporis', 'The moment Alice felt a little timidly, for she had sat down again very sadly and quietly, and looked along the course, here and there. There was a dead silence instantly, and neither of the bottle.', NULL),
(62, 'nvre', 'Est repudiandae nulla eum animi et vel. Itaque sit quod voluptatem doloremque molestiae. Voluptatem saepe et ipsa hic delectus numquam. Neque in quibusdam possimus.', 'Rabbit asked. \'No, I give you fair warning,\' shouted the Queen. \'I haven\'t opened it yet,\' said the Hatter. He had been (Before she had wept when she next peeped out the Fish-Footman was gone, and,.', 'Kentucky', '524', 'neque', 'Alice remarked. \'Oh, you foolish Alice!\' she answered herself. \'How can you learn lessons in here? Why, there\'s hardly room for YOU, and no one listening, this time, sat down in a deep sigh, \'I was.', NULL),
(63, 'tewz', 'Accusantium nulla voluptatem voluptatem ipsa. Consequuntur vel voluptatibus dolor aut. Et sequi qui ut numquam sint rerum iste. Ut vitae necessitatibus architecto.', 'Majesty,\' said Two, in a day is very confusing.\' \'It isn\'t,\' said the Caterpillar contemptuously. \'Who are YOU?\' Which brought them back again to the tarts on the floor, as it was quite tired of.', 'Wisconsin', '957', 'ullam', 'Alice went timidly up to her to begin.\' He looked at Alice. \'It goes on, you know,\' said Alice, who felt very curious to know what a delightful thing a bit!\' said the Dodo. Then they both bowed low,.', NULL),
(64, 'sonz', 'Cupiditate at blanditiis ratione id corrupti ipsam ducimus veritatis. Magnam sint dignissimos fuga voluptas. Blanditiis nesciunt itaque voluptas aperiam dignissimos corporis voluptas eligendi.', 'YOU like cats if you please! \"William the Conqueror, whose cause was favoured by the whole pack of cards, after all. \"--SAID I COULD NOT SWIM--\" you can\'t be Mabel, for I know all sorts of things--I.', 'Kansas', '565', 'magnam', 'Knave of Hearts, carrying the King\'s crown on a summer day: The Knave did so, and giving it something out of a muchness\"--did you ever see such a rule at processions; \'and besides, what would happen.', NULL),
(65, 'zyuo', 'Distinctio itaque est animi rerum atque sequi culpa. Similique labore deserunt atque aliquam dignissimos.', 'Majesty!\' the Duchess said to a mouse, you know. Come on!\' So they had a consultation about this, and she soon found herself safe in a deep voice, \'What are tarts made of?\' \'Pepper, mostly,\' said.', 'Arizona', '318', 'id', 'Mouse heard this, it turned a corner, \'Oh my ears and the Queen shrieked out. \'Behead that Dormouse! Turn that Dormouse out of the house opened, and a Long Tale They were just beginning to grow to.', NULL),
(66, 'zldk', 'Blanditiis earum quia reiciendis vero. Eum illum voluptatem dolores veniam blanditiis blanditiis. Adipisci itaque quos pariatur eos est voluptatem quam.', 'Gryphon interrupted in a hot tureen! Who for such a curious dream, dear, certainly: but now run in to your tea; it\'s getting late.\' So Alice began to repeat it, but her voice sounded hoarse and.', 'California', '390', 'et', 'Alice, as she passed; it was only a mouse that had fallen into a pig,\' Alice quietly said, just as she went hunting about, and called out, \'First witness!\' The first question of course you know.', NULL),
(67, 'mwkd', 'Sint laboriosam porro necessitatibus quibusdam. Repellendus quia deserunt minus voluptate. Accusantium repellat necessitatibus nam. Aliquid nihil voluptatibus illum dolore.', 'I like being that person, I\'ll come up: if not, I\'ll stay down here! It\'ll be no use in crying like that!\' said Alice very meekly: \'I\'m growing.\' \'You\'ve no right to think,\' said Alice indignantly,.', 'RhodeIsland', '260', 'sint', 'I\'ll set Dinah at you!\' There was no \'One, two, three, and away,\' but they all quarrel so dreadfully one can\'t hear oneself speak--and they don\'t give birthday presents like that!\' But she waited.', NULL),
(68, 'fwyl', 'Et omnis vero sunt rerum sit deleniti. Eveniet excepturi et deserunt eligendi vero voluptatibus. Ipsam deleniti excepturi facere officiis. Quaerat consectetur sed vitae consequatur recusandae expedita. Quidem dolor distinctio ut dolores dolorum.', 'There was exactly one a-piece all round. (It was this last word with such a neck as that! No, no! You\'re a serpent; and there\'s no use denying it. I suppose Dinah\'ll be sending me on messages next!\'.', 'Alaska', '990', 'aut', 'Duchess said in a soothing tone: \'don\'t be angry about it. And yet I wish you would seem to dry me at all.\' \'In that case,\' said the Dodo, pointing to Alice an excellent opportunity for croqueting.', NULL),
(69, 'yikq', 'Eum libero ut assumenda voluptatem tempora delectus. Id aut quod non.', 'Alice. \'I\'ve tried every way, and the pair of gloves and the blades of grass, but she added, \'and the moral of THAT is--\"Take care of themselves.\"\' \'How fond she is such a new kind of sob, \'I\'ve.', 'Oregon', '072', 'corporis', 'It\'s by far the most important piece of it in her lessons in the long hall, and wander about among those beds of bright flowers and the sounds will take care of the others looked round also, and all.', NULL),
(70, 'igyi', 'Molestias nam illum sed autem voluptas veritatis quo. Voluptas et quia et quis voluptatum est. Voluptates ab aut ut sit vitae voluptatem sed.', 'Gryphon. Alice did not appear, and after a minute or two the Caterpillar decidedly, and he wasn\'t one?\' Alice asked. \'We called him Tortoise because he was obliged to have finished,\' said the.', 'RhodeIsland', '595', 'vel', 'Alice was beginning to think about it, you may SIT down,\' the King said to the law, And argued each case with MINE,\' said the White Rabbit hurried by--the frightened Mouse splashed his way through.', NULL),
(71, 'vopu', 'Eaque et possimus labore recusandae ea. Voluptas et omnis necessitatibus adipisci. Sit aspernatur fugit consequatur voluptatem est sit.', 'BEE,\" but it had struck her foot! She was moving them about as much as she could. \'No,\' said Alice. \'Off with her face like the name: however, it only grinned when it saw mine coming!\' \'How do you.', 'Montana', '395', 'rerum', 'Alice ventured to ask. \'Suppose we change the subject. \'Ten hours the first witness,\' said the Lory. Alice replied in an offended tone, and added \'It isn\'t a bird,\' Alice remarked. \'Right, as.', NULL),
(72, 'pchk', 'Cupiditate sit accusamus sit nemo dolorem dolores non excepturi. Dolores fugiat dolores recusandae reprehenderit deleniti tempora. Eius nobis aut perspiciatis enim aut libero dolor.', 'The Hatter was the Hatter. \'You might just as if he wasn\'t going to happen next. \'It\'s--it\'s a very decided tone: \'tell her something about the temper of your flamingo. Shall I try the effect: the.', 'Arkansas', '963', 'eveniet', 'I should frighten them out of the leaves: \'I should like to drop the jar for fear of killing somebody, so managed to put the Dormouse shall!\' they both sat silent for a great many more than that, if.', NULL),
(73, 'zmuf', 'Nihil sequi eos dolor provident nulla. At est sint odio atque enim. Rerum perspiciatis id quod nam rerum reiciendis et.', 'While the Duchess and the pattern on their hands and feet, to make herself useful, and looking anxiously round to see if she meant to take MORE than nothing.\' \'Nobody asked YOUR opinion,\' said.', 'Wyoming', '123', 'asperiores', 'I shall fall right THROUGH the earth! How funny it\'ll seem, sending presents to one\'s own feet! And how odd the directions will look! ALICE\'S RIGHT FOOT, ESQ. HEARTHRUG, NEAR THE FENDER, (WITH.', NULL),
(74, 'nbaf', 'Ea et vel et quos aut. Consequuntur labore necessitatibus ipsam facilis hic. Et iste deleniti quod ad error.', 'March Hare and the fall was over. However, when they met in the house, and wondering what to do with this creature when I was a little bit of mushroom, and crawled away in the air. This time Alice.', 'Illinois', '062', 'et', 'I can say.\' This was not here before,\' said Alice,) and round Alice, every now and then the Rabbit\'s voice along--\'Catch him, you by the way, was the White Rabbit, \'and that\'s the jury, in a louder.', NULL),
(75, 'uslu', 'Labore ut molestiae in corporis sed sequi nihil maxime. Voluptatem dolore et sit dolorem quis dicta officia. Nam sequi impedit blanditiis fuga.', 'I could say if I chose,\' the Duchess replied, in a tone of this sort in her life, and had no idea how to speak first, \'why your cat grins like that?\' \'It\'s a Cheshire cat,\' said the Dormouse,.', 'Virginia', '933', 'alias', 'And she squeezed herself up and walking away. \'You insult me by talking such nonsense!\' \'I didn\'t mean it!\' pleaded poor Alice. \'But you\'re so easily offended, you know!\' The Mouse only growled in.', NULL),
(76, 'vkzw', 'Asperiores ut dolor incidunt aperiam dolor. Esse ea voluptas quia numquam accusamus laboriosam. Reprehenderit dolorem assumenda fugiat libero earum laudantium. Porro cupiditate non reiciendis repellat labore.', 'Alice loudly. \'The idea of having nothing to what I should like it very hard indeed to make out who I WAS when I got up very carefully, nibbling first at one end to the King, \'and don\'t look at the.', 'California', '617', 'commodi', 'Alice to herself. Imagine her surprise, when the tide rises and sharks are around, His voice has a timid voice at her with large round eyes, and half believed herself in Wonderland, though she felt.', NULL),
(77, 'zvky', 'Perferendis vel fugiat ipsam error ex nam non. Sunt nam ut quia nihil aliquid. Id iusto ut harum in quo sed aperiam. Ipsa quos nisi ducimus aliquid et.', 'Alice, seriously, \'I\'ll have nothing more happened, she decided on going into the air. \'--as far out to be seen--everything seemed to be a grin, and she thought it must make me giddy.\' And then,.', 'Nevada', '941', 'reprehenderit', 'Alice, as she added, \'and the moral of that is, but I shall have some fun now!\' thought Alice. \'I don\'t think it\'s at all a proper way of keeping up the fan and a crash of broken glass. \'What a pity.', NULL),
(78, 'rhti', 'Esse animi vel consectetur quis sit est. Id voluptas facilis ex. Molestias nesciunt non qui aut nihil. Animi deserunt officiis repellendus aut unde repellendus aliquid voluptatibus. Dolorem et vero illo doloribus.', 'Alice thought over all the time it vanished quite slowly, beginning with the Mouse replied rather crossly: \'of course you know that cats COULD grin.\' \'They all can,\' said the Gryphon, and the Queen.', 'Michigan', '258', 'consequatur', 'The Fish-Footman began by taking the little magic bottle had now had its full effect, and she soon found herself falling down a jar from one minute to another! However, I\'ve got to?\' (Alice had no.', NULL),
(79, 'xmbj', 'Qui voluptas veniam et molestiae. Eum et illo velit exercitationem reprehenderit a ipsum.', 'It\'ll be no chance of getting her hands on her toes when they passed too close, and waving their forepaws to mark the time, while the rest of the shelves as she could, for the baby, the shriek of.', 'Louisiana', '286', 'dolor', 'King sharply. \'Do you mean that you had been of late much accustomed to usurpation and conquest. Edwin and Morcar, the earls of Mercia and Northumbria, declared for him: and even Stigand, the.', NULL),
(80, 'bzki', 'Dolore voluptatem facilis corrupti nostrum ducimus. Eum exercitationem ut aut nobis eius praesentium. Nesciunt eos unde rem sed minima sunt.', 'Hatter. \'Nor I,\' said the Mock Turtle had just begun to dream that she was always ready to sink into the teapot. \'At any rate I\'ll never go THERE again!\' said Alice timidly. \'Would you like the look.', 'Michigan', '945', 'et', 'Hatter: \'but you could manage it?) \'And what an ignorant little girl or a worm. The question is, what did the Dormouse indignantly. However, he consented to go on. \'And so these three little.', NULL),
(81, 'ekmh', 'Autem itaque sit iure voluptates. Rerum reiciendis id sequi tenetur. Delectus pariatur dolorem molestias molestias sed. Voluptatibus qui ducimus beatae distinctio.', 'You see the Mock Turtle angrily: \'really you are painting those roses?\' Five and Seven said nothing, but looked at poor Alice, who had been anxiously looking across the garden, where Alice could.', 'Florida', '226', 'recusandae', 'White Rabbit interrupted: \'UNimportant, your Majesty means, of course,\' said the Caterpillar; and it put the hookah out of THIS!\' (Sounds of more energetic remedies--\' \'Speak English!\' said the.', NULL),
(82, 'tnru', 'Et libero id nemo. Ut provident molestiae necessitatibus saepe. Adipisci libero vero voluptas et pariatur. Dignissimos et possimus omnis expedita ducimus quis iusto deserunt. Dolorem eum velit aut dolor amet accusantium et.', 'Dodo replied very politely, \'if I had our Dinah here, I know who I am! But I\'d better take him his fan and the second verse of the shelves as she passed; it was done. They had a door leading right.', 'District of Columbia', '801', 'vel', 'Alice thought she might as well wait, as she was shrinking rapidly; so she went back to the little door, so she felt sure it would be wasting our breath.\" \"I\'ll be judge, I\'ll be jury,\" Said cunning.', NULL);
INSERT INTO `model_legislations_dummy` (`mleg_id`, `title_of_model_legislation`, `text_of_model_legislation`, `summary`, `state`, `type`, `display_file_name`, `purpose`, `preamble`) VALUES
(83, 'dxtu', 'Consequuntur placeat laudantium aspernatur facere eius omnis. Quia nemo earum distinctio dolores dignissimos. Quod voluptatem corporis reiciendis doloremque. Voluptatem illo minima architecto sunt facilis sed ut.', 'I\'ve nothing to do: once or twice, half hoping that they couldn\'t see it?\' So she went on just as she listened, or seemed to be sure, she had read several nice little histories about children who.', 'Illinois', '671', 'quo', 'FENDER, (WITH ALICE\'S LOVE). Oh dear, what nonsense I\'m talking!\' Just then her head pressing against the roof of the busy farm-yard--while the lowing of the garden: the roses growing on it (as she.', NULL),
(84, 'kgbp', 'Et deserunt et rerum quis vel laudantium. Blanditiis ducimus quis nam placeat quae ea vitae. Consequatur facere magnam non labore natus. Reiciendis quis rerum nisi quas. Provident et eos architecto ea dolore laudantium fuga veniam.', 'Which way?\', holding her hand in hand with Dinah, and saying to herself, \'I wonder what Latitude or Longitude either, but thought they were nowhere to be Number One,\' said Alice. \'That\'s the reason.', 'RhodeIsland', '751', 'corrupti', 'I didn\'t!\' interrupted Alice. \'You must be,\' said the Lory, who at last in the direction in which the cook was busily stirring the soup, and seemed not to be no chance of her hedgehog. The hedgehog.', NULL),
(85, 'ccwy', 'Quia consequuntur odit praesentium et aliquid. Quia et ad occaecati omnis aliquam. Veritatis itaque dolores provident in ut aut voluptate aut. Aliquid cum fugit debitis odio commodi maiores rerum.', 'Alice, in a minute, nurse! But I\'ve got to the jury, in a trembling voice to its feet, \'I move that the hedgehog a blow with its wings. \'Serpent!\' screamed the Queen. \'I never heard it say to this:.', 'Florida', '182', 'voluptatem', 'Queen\'s hedgehog just now, only it ran away when it had no idea what to beautify is, I suppose?\' \'Yes,\' said Alice in a day is very confusing.\' \'It isn\'t,\' said the Dormouse: \'not in that soup!\'.', NULL),
(86, 'eplk', 'Non illum ut voluptatem sed qui. Et illum nulla exercitationem odio. Voluptas asperiores voluptatem voluptate nam.', 'I think--\' (she was so full of smoke from one foot up the little creature down, and was suppressed. \'Come, that finished the guinea-pigs!\' thought Alice. \'I wonder what they\'ll do next! As for.', 'Massachusetts', '211', 'et', 'King. \'Shan\'t,\' said the Footman, and began an account of the accident, all except the Lizard, who seemed to be seen: she found to be Number One,\' said Alice. \'Why?\' \'IT DOES THE BOOTS AND SHOES.\'.', NULL),
(87, 'idoc', 'Exercitationem pariatur voluptas odio sequi. Ad soluta optio cum hic sint molestiae. Ipsa rerum doloribus nulla dolores. Aperiam nobis iusto neque animi sed voluptatum aliquid. Tempora adipisci laborum a harum quo.', 'I think I can do no more, whatever happens. What WILL become of it; then Alice, thinking it was the matter with it. There could be NO mistake about it: it was certainly not becoming. \'And that\'s the.', 'Arizona', '183', 'culpa', 'I can say.\' This was such a new idea to Alice, very loudly and decidedly, and the White Rabbit. She was a most extraordinary noise going on rather better now,\' she said, \'for her hair goes in such.', NULL),
(88, 'ouem', 'Quam perferendis incidunt culpa enim aut. Id temporibus voluptas quam eum voluptate. Et eum incidunt reprehenderit ullam accusantium perferendis quibusdam non.', 'Majesty,\' said the Pigeon went on, \'you see, a dog growls when it\'s angry, and wags its tail about in the newspapers, at the Hatter, \'or you\'ll be telling me next that you had been to a mouse, you.', 'Georgia', '571', 'sit', 'Alice took up the fan and gloves. \'How queer it seems,\' Alice said very politely, \'for I can\'t see you?\' She was moving them about as curious as it is.\' \'Then you should say \"With what porpoise?\"\'.', NULL),
(89, 'yuep', 'Molestiae assumenda sint id quod voluptatem eos tenetur. Neque molestiae veniam et alias hic earum expedita facilis.', 'Father William replied to his son, \'I feared it might happen any minute, \'and then,\' thought she, \'what would become of you? I gave her answer. \'They\'re done with blacking, I believe.\' \'Boots and.', 'California', '096', 'sed', 'I wonder?\' Alice guessed who it was, even before she came suddenly upon an open place, with a sigh: \'he taught Laughing and Grief, they used to say.\' \'So he did, so he did,\' said the Cat, \'if you.', NULL),
(90, 'mzbs', 'Assumenda reiciendis doloremque doloribus quia. Nemo aut expedita est consequuntur. Facere aut et dolorum laboriosam.', 'Alice had learnt several things of this was not a moment like a candle. I wonder what you\'re talking about,\' said Alice. \'Call it what you were down here with me! There are no mice in the trial.', 'NorthDakota', '984', 'aliquid', 'March Hare, \'that \"I breathe when I was a little glass box that was trickling down his cheeks, he went on growing, and, as she tucked her arm affectionately into Alice\'s, and they lived at the.', NULL),
(91, 'bpcd', 'Velit sequi quidem doloremque libero rerum. Aliquam praesentium voluptatum et facere. Dicta maxime aliquid corporis a velit.', 'TO YOU,\"\' said Alice. \'Come on, then,\' said the Dormouse; \'--well in.\' This answer so confused poor Alice, \'to pretend to be sure, she had never done such a curious dream!\' said Alice, swallowing.', 'Texas', '000', 'odit', 'Footman, \'and that for two Pennyworth only of beautiful Soup? Pennyworth only of beautiful Soup? Pennyworth only of beautiful Soup? Beau--ootiful Soo--oop! Beau--ootiful Soo--oop! Beau--ootiful.', NULL),
(92, 'bwbp', 'Vel alias dolor est vero quas quidem consectetur. Ut sapiente voluptate sint doloremque tempore quo aperiam. Et et voluptas dolorum consequatur et omnis. Delectus et saepe voluptatem enim.', 'Caterpillar. Alice said very humbly; \'I won\'t interrupt again. I dare say you never had fits, my dear, I think?\' \'I had NOT!\' cried the Mock Turtle in the air: it puzzled her too much, so she helped.', 'District of Columbia', '251', 'rerum', 'Alice as he spoke. \'A cat may look at all for any of them. However, on the floor: in another moment, when she first saw the Mock Turtle; \'but it sounds uncommon nonsense.\' Alice said to herself;.', NULL),
(93, 'nvrr', 'Quis eos rem suscipit ut. Placeat suscipit voluptates amet dolor et sit. Laudantium omnis aut aperiam nesciunt. Nobis in et suscipit magnam officiis eaque harum.', 'It quite makes my forehead ache!\' Alice watched the Queen said to herself as she spoke. \'I must be on the slate. \'Herald, read the accusation!\' said the Caterpillar took the hookah out of sight,.', 'Illinois', '055', 'et', 'Queen to-day?\' \'I should have croqueted the Queen\'s voice in the last words out loud, and the Hatter continued, \'in this way:-- \"Up above the world go round!\"\' \'Somebody said,\' Alice whispered,.', NULL),
(94, 'eqqq', 'Sapiente est ullam ipsa esse sint enim. Non id et rerum consectetur culpa. Quibusdam sequi voluptate rerum est omnis quo.', 'Alice dodged behind a great many more than three.\' \'Your hair wants cutting,\' said the Duchess; \'and the moral of that dark hall, and close to her feet, for it now, I suppose, by being drowned in my.', 'Minnesota', '796', 'veritatis', 'Mock Turtle would be offended again. \'Mine is a long and a pair of the house down!\' said the Caterpillar took the regular course.\' \'What was that?\' inquired Alice. \'Reeling and Writhing, of course,.', NULL),
(95, 'qwgh', 'Dignissimos accusamus non at alias est magnam quo. Qui et quasi exercitationem ad earum aliquam. Sint atque dicta perferendis cumque quo eos deleniti adipisci. Distinctio laudantium sunt voluptatibus perspiciatis quo.', 'Caterpillar took the opportunity of showing off her unfortunate guests to execution--once more the pig-baby was sneezing on the floor, as it is.\' \'I quite forgot how to speak with. Alice waited a.', 'Utah', '586', 'qui', 'Alice, swallowing down her anger as well as she swam nearer to make out who I am! But I\'d better take him his fan and gloves--that is, if I shall fall right THROUGH the earth! How funny it\'ll seem.', NULL),
(96, 'hihk', 'Eius delectus ullam et quia quo iusto aut. Voluptatem dolores non alias aperiam reprehenderit voluptatem. Debitis quia illo dolorem excepturi voluptate aut. Qui sunt assumenda consequatur vel autem iste. Voluptatum accusamus rerum eius officiis molestiae.', 'Alice whispered to the porpoise, \"Keep back, please: we don\'t want YOU with us!\"\' \'They were obliged to have any pepper in my size; and as he spoke, and the happy summer days. THE.', 'Maine', '087', 'dolor', 'However, the Multiplication Table doesn\'t signify: let\'s try the patience of an oyster!\' \'I wish I could not make out who was passing at the proposal. \'Then the eleventh day must have been changed.', NULL),
(97, 'qgms', 'Nostrum quae provident consequatur sequi molestiae voluptatem voluptatem. Vel eligendi similique ipsum repudiandae accusamus hic. Eligendi inventore aliquam culpa veritatis maiores nulla aut.', 'Five, \'and I\'ll tell you my history, and you\'ll understand why it is all the jurymen are back in a Little Bill It was the White Rabbit cried out, \'Silence in the middle, being held up by a row of.', 'Iowa', '789', 'ut', 'There was a very deep well. Either the well was very likely true.) Down, down, down. Would the fall NEVER come to the Queen. \'Can you play croquet?\' The soldiers were always getting up and picking.', NULL),
(98, 'avhj', 'Est dicta explicabo eaque porro necessitatibus voluptas. Suscipit quam non tempore eum aut. Quae quia et dolor vitae tempore officia in.', 'Hatter began, in a large cat which was a dispute going on shrinking rapidly: she soon made out that the hedgehog to, and, as they all stopped and looked at Alice. \'I\'M not a VERY unpleasant state of.', 'Utah', '997', 'adipisci', 'I\'m I, and--oh dear, how puzzling it all is! I\'ll try if I like being that person, I\'ll come up: if not, I\'ll stay down here! It\'ll be no use in the other. \'I beg your pardon!\' she exclaimed in a.', NULL),
(99, 'kmxu', 'Dolores aliquid ipsam eaque maxime dolor ea consequuntur laudantium. Eveniet quia dolor nemo doloremque illum officiis. Doloribus eum facilis neque similique in.', 'Alice. \'That\'s the judge,\' she said to the company generally, \'You are old,\' said the Duck: \'it\'s generally a ridge or furrow in the newspapers, at the mushroom for a minute, trying to box her own.', 'Oklahoma', '037', 'maiores', 'I wonder who will put on his spectacles. \'Where shall I begin, please your Majesty,\' said Two, in a low voice, \'Why the fact is, you know. Come on!\' \'Everybody says \"come on!\" here,\' thought Alice,.', NULL),
(100, 'vskh', 'Reiciendis voluptas velit dolores et alias minima libero. Saepe corporis aliquid sed vero adipisci eos nulla.', 'Alice, and she went round the rosetree; for, you see, as well be at school at once.\' And in she went. Once more she found she could not possibly reach it: she could see her after the rest of the.', 'Minnesota', '713', 'et', 'Caterpillar The Caterpillar and Alice could think of nothing else to say \'Drink me,\' but the great wonder is, that I\'m perfectly sure I have ordered\'; and she sat down with one elbow against the.', NULL),
(101, 'pdrq', 'Modi exercitationem error nesciunt ullam. Dignissimos dolore soluta voluptatem fugiat aliquam labore. Sint reiciendis tempore temporibus consectetur voluptatem. Omnis beatae harum dolores dignissimos. Veniam enim saepe quia.', 'Gryphon: and Alice was more hopeless than ever: she sat down with wonder at the Footman\'s head: it just missed her. Alice caught the baby joined):-- \'Wow! wow! wow!\' \'Here! you may stand down,\'.', 'Virginia', '497', 'ut', 'The Panther took pie-crust, and gravy, and meat, While the Duchess sneezed occasionally; and as it can talk: at any rate,\' said Alice: \'--where\'s the Duchess?\' \'Hush! Hush!\' said the Caterpillar.', NULL),
(102, 'jmlj', 'Dolorem quo vitae labore autem perferendis repellendus et. Ea et sed qui voluptates. Aut odio in at ab quia. Et fugiat dolor eum molestiae.', 'Duck: \'it\'s generally a ridge or furrow in the pictures of him), while the Mouse was bristling all over, and both the hedgehogs were out of a bottle. They all made a rush at the stick, running a.', 'Pennsylvania', '845', 'quia', 'I\'m mad?\' said Alice. \'Why not?\' said the Duchess; \'and that\'s a fact.\' Alice did not at all comfortable, and it was too late to wish that! She went in without knocking, and hurried upstairs, in.', NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `model_legislations_dummy`
--
ALTER TABLE `model_legislations_dummy`
  ADD PRIMARY KEY (`mleg_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `model_legislations_dummy`
--
ALTER TABLE `model_legislations_dummy`
  MODIFY `mleg_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=103;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
